imports:
    - path: deploy-template.jinja

resources:
    - name: deploy
      type: deploy-template.jinja
      properties:
          zone: us-central1-a
          subnetwork: us-central1
          user: ranl
          #password:
          slackToken: token_for_slack_bot
          fernetKey: fernetKey_for_airflow
          secretKey: secretKey_for_airflow_webserver
          botUserID: slack_bot_id
          remoteLogFolder: gs_bucket_for_the_logs
          seuronImage: ranlu/air-tasks:airflow2
          project: segmentation
          managerIP0: 172.31.31.249
          instanceTypeManager: e2-standard-4
          instanceTypeGPUWorker: n1-highmem-4
          instanceTypeAtomicWorker: e2-standard-32
          instanceTypeCompositeWorker: n2-highmem-96
          gpuWorkerAcceleratorType: nvidia-tesla-t4
          composeLocation: https://raw.githubusercontent.com/seung-lab/seuron/airflow2/deploy/docker-compose-CeleryExecutor.yml
