imports:
    - path: deploy-template.jinja

resources:
    - name: deploy
      type: deploy-template.jinja
      properties:
          zone: us-east1-b
          image: infrakit/devbundle:master-2662
          configRoot: https://raw.githubusercontent.com/seung-lab/seuron_examples/alex_pinky100/latest/swarm/
          configURL: https://raw.githubusercontent.com/seung-lab/seuron_examples/alex_pinky100/latest/metadata/google/export.ikt
          user: jabae
          #password:
          project: errordetection
          managerIP0: 172.31.255.250
          managerIP1: 172.31.255.251
          managerIP2: 172.31.255.252
          managerIP3: 172.31.255.253
          managerIP4: 172.31.255.254
          sizeManager: 3
          sizeWorker: 1
          instanceTypeManager: n1-standard-4 # make sure instance has > 6 GB of ram for postgres deployment
          instanceTypeWorker: f1-micro
          composeLocation: https://raw.githubusercontent.com/jabae/seuron/alex/deploy/docker-compose-CeleryExecutor.yml
