imports:
    - path: common.py
    - path: networks.py
    - path: workers.py
    - path: manager.py
    - path: deployment.py

resources:
    - name: deployment
      type: deployment.py
      properties:
          zone: us-east1-c
          subnetwork: us-east1
          seuronImage: ranlu/seuron:main
          project: segmentation
          managerMachineType: e2-medium
          composeLocation: https://raw.githubusercontent.com/seung-lab/seuron/main/deploy/docker-compose-CeleryExecutor.yml
          slack:
            botToken: # bot token for slack
          nginx:
            user: # nginx username
            password: # nginx password, set it to null if you do not want a password
          airflow:
            fernetKey: FERNET_KEY
            secretKey: SECRET_KEY
            remoteLogFolder: # GCS path to save airflow logs
            user: # username for airflow services
            password: # password for airflow services
          postgres:
            user: # postgres username
            password: # postgres password
            database: # postgres database for airflow
          workerInstanceGroups:
            - type: gpu
              zone: us-east1-c
              subnetwork: us-east1
              machineType: n1-highmem-4
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 4
            - type: gpu
              zone: us-central1-c
              subnetwork: us-central1
              machineType: n1-highmem-4
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 4
            - type: gpu
              zone: us-west1-b
              subnetwork: us-west1
              machineType: n1-highmem-4
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 4
            - type: gpu
              zone: us-west2-b
              subnetwork: us-west2
              machineType: n1-highmem-4
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 4
            - type: gpu
              zone: us-east4-b
              subnetwork: us-east4
              machineType: n1-highmem-4
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 4
            - type: atomic
              zone: us-east1-c
              subnetwork: us-east1
              machineType: e2-standard-32
              preemptible: True
              sizeLimit: 100
            - type: composite
              zone: us-east1-c
              subnetwork: us-east1
              machineType: e2-standard-32
              preemptible: False
              sizeLimit: 1
            - type: igneous
              zone: us-east1-c
              subnetwork: us-east1
              machineType: e2-standard-32
              preemptible: True
              sizeLimit: 50
            - type: custom-cpu
              zone: us-east1-c
              subnetwork: us-east1
              machineType: e2-standard-32
              preemptible: True
              sizeLimit: 50
            - type: custom-gpu
              zone: us-east1-c
              subnetwork: us-east1
              machineType: n1-highmem-8
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              workerImage: ranlu/air-tasks:airflow2
              preemptible: True
              sizeLimit: 4
            - type: synaptor-cpu
              zone: us-east1-c
              subnetwork: us-east1
              machineType: e2-highmem-4
              preemptible: True
              sizeLimit: 10
            - type: synaptor-gpu
              zone: us-east1-c
              subnetwork: us-east1
              machineType: n1-highmem-8
              gpuWorkerAcceleratorType: nvidia-tesla-t4
              preemptible: True
              sizeLimit: 10
            - type: synaptor-seggraph
              zone: us-east1-c
              subnetwork: us-east1
              machineType: n2d-highmem-32
              preemptible: False
              sizeLimit: 1
          firewallAllowedIPRanges:
              - 128.112.0.0/16
