imports:
    - path: deploy-template.jinja

resources:
    - name: deploy
      type: deploy-template.jinja
      properties:
          zone: us-central1-a
          subnetwork: us-central1
          configRoot: https://raw.githubusercontent.com/seung-lab/seuron_examples/ranl_testing/latest/swarm/
          configURL: https://raw.githubusercontent.com/seung-lab/seuron_examples/ranl_testing/latest/metadata/google/export.ikt
          user: ranl
          #password:
          slackToken: token_for_slack_bot
          fernetKey: fernetKey_for_airflow
          botUserID: slack_bot_id
          remoteLogFolder: gs_bucket_for_the_logs
          seuronImage: ranlu/air-tasks:ranl_testing
          #slackToken:
          #workerID:
          project: segmentation
          managerIP0: 172.31.31.249
          managerIP1: 172.31.31.250
          managerIP2: 172.31.31.251
          managerIP3: 172.31.31.252
          managerIP4: 172.31.31.254
          databaseIP0: 172.31.31.253
          sizeManager: 1
          sizeDatabase: 0
          sizeWorker: 0
          instanceTypeManager: n1-standard-4
          instanceTypeDatabase: n1-standard-4
          instanceTypeGPUWorker: n1-highmem-4
          instanceTypeAtomicWorker: n1-highmem-32
          instanceTypeCompositeWorker: n1-highmem-96
          composeLocation: https://raw.githubusercontent.com/seung-lab/seuron/ranl_testing/deploy/docker-compose-CeleryExecutor.yml
