imports:
    - path: deploy-template.jinja

resources:
    - name: deploy
      type: deploy-template.jinja
      properties:
          zone: us-east1-b
          image: infrakit/devbundle:master-2662
          configRoot: https://raw.githubusercontent.com/wongwill86/examples/ranl_basil_full/latest/swarm/
          configURL: https://raw.githubusercontent.com/wongwill86/examples/ranl_basil_full/latest/metadata/google/export.ikt
          user: ranl
          #password:
          project: test_watershed
          managerIP0: 172.31.31.249
          managerIP1: 172.31.31.250
          managerIP2: 172.31.31.251
          managerIP3: 172.31.31.252
          managerIP4: 172.31.31.253
          databaseIP0: 172.31.31.254
          sizeManager: 1
          sizeDatabase: 1
          sizeWorker: 1
          instanceTypeManager: n1-standard-16
          instanceTypeDatabase: n1-standard-64
          instanceTypeWorker: f1-micro
          composeLocation: https://raw.githubusercontent.com/wongwill86/air-tasks/ranl_basil_full/deploy/docker-compose-CeleryExecutor.yml
