imports:
    - path: deploy-template.jinja

resources:
    - name: deploy
      type: deploy-template.jinja
      properties:
          zone: us-central1-a
          image: infrakit/devbundle:master-2662
          configRoot: https://raw.githubusercontent.com/seung-lab/seuron_examples/ranl_upgrade/latest/swarm/
          configURL: https://raw.githubusercontent.com/seung-lab/seuron_examples/ranl_upgrade/latest/metadata/google/export.ikt
          user: ranl
          #password:
          project: segmentation
          managerIP0: 172.31.31.249
          managerIP1: 172.31.31.250
          managerIP2: 172.31.31.251
          managerIP3: 172.31.31.252
          managerIP4: 172.31.31.254
          databaseIP0: 172.31.31.253
          sizeManager: 1
          sizeDatabase: 1
          sizeWorker: 1
          instanceTypeManager: n1-standard-64
          instanceTypeDatabase: n1-standard-64
          instanceTypeWorker: f1-micro
          composeLocation: https://raw.githubusercontent.com/seung-lab/seuron/ranl_upgrade/deploy/docker-compose-CeleryExecutor.yml
